### ISSUE TITLE
Impossible to order if admin determines carrier?

### ISSUE THREAD

**Issue by luzat** [shipcloud/shipcloud-for-woocommerce#199]
For a shop which uses multiple carriers where the shop owner should determine the carrier to use, I configured the plugin accordingly: ![image](https://user-images.githubusercontent.com/1327084/112834788-b588c400-9098-11eb-85f3-10459e2a0d7f.png)

Unfortunately, this seems to imply that no rates are added for shipcloud in `WC_Shipcloud_Shipping::calculate_shipping` and in turn the shipping method is not shown when placing an order. Isn't it possible to have the owner choose the carrier and use the shipcloud method? I guess in this case it would be best to create a different shipping method and only use shipcloud.io to create labels?

**Comment by luzat** [comment]
To be clear: I guess this is not a bug, but intended usage is to create a different shipment method in this case and have the admin assign the carrier later on?

**Comment by andrecedik** [comment]
Yes it is intended to be this way. Either the customer selects the shipping method in the checkout. The list is based on the carrier-service-combination that has been activated in the settings by the merchant. The other option is to let the merchant decide which carrier and service should be used. 

The only difference is that while the customer can select carrier and service in the checkout, the merchant still can select another carrier when creating the shipping label. 

In the latter case, the merchant would have to configure shipping methods using the WooCommerce means. This honestly is the best case to handle shipping methods at the moment since the merchant can then decide what the customer should be charged. 

If you understand German I encourage you to read [my blogpost](http://blog.cedik.de/live-versandkostenberechnung-im-checkout-und-warum-sie-nicht-funktioniert/) about the issues one is facing when showing real-time shipping quotes.

I know the current way is not the best approach to this issue and it will be one of the things we will fix in version 2.0 of the plugin.

**Comment by luzat** [comment]
Thanks for clarifying. I feel it's a bit unclear from within the plugin how it is supposed to work. It may be useful to add this to the option description. I am currently implementing this for a shop: I am using a custom shipping method with customized code to determine pricing and shipping class (by actually using dimensions and weight, even though the real packaging might end up being slightly different, given the issues that you've described, too), and have the shop owner create the shipping labels afterwards.

There are various special cases and I imagine that a general solution would be hard. It might be nice if the plugin offered a few action/filter hooks in the future, though, for example to automatically select a shipping method through code or to programmatically create a list of parcels for an order to make it available for the plugin.
